name: kafka
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
  - {name: zookeeper_release, version: latest}
  - {name: kafka_release, version: latest}
stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: zoo_node
    instances: 3
    azs: [z1]
    jobs:
    - name: zookeeper_server
      release: zookeeper_release
      provides:
        zookeeper: {as: zookeeper}
      consumes:
        zookeeper: {from: zookeeper}
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    networks:
      - name: default
  - name: kafka_node
    instances: 5
    azs: [z1]
    jobs:
    - name: kafka_server
      release: kafka_release
      provides:
        kafka: {as: kafka}
      consumes:
        zookeeper: {from: zookeeper}
        kafka: {from: kafka}
      properties:
        auto_create_topics: true
        default_replication_factor: 1
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    networks:
      - name: default

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000